Combinatorialize tarpc feature tests.
In the CI github workflow, in the job test-with-features, make a
separate matrix dimension for each Cargo feature to enable. Github
Actions should combine these features, so that we get more test coverage
of different feature enablements.

This also introduces a minor breaking change by renaming
serde_transport::{tcp,unix}::Connect to {Tcp,Unix}Connect.

Rationale: enabling all combinations actually revealed a compile_fail
error that only arises when certain combinations of features are
enabled! In the serde_transport module, there are two submodules, tcp
and unix, which each provide a Connect type. When only one of the
tcp/unix features is enabled, there is a unique path to the Connect
type, and the name gets shortened in compile error messages. When both
features are enabled, there is no longer a unique path to the Connect
type, and the compile error messages print the full path.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,22 +24,28 @@ jobs:
   test:
     name: Test
     runs-on: ubuntu-latest
-    steps:
-      - name: Cancel previous
-        uses: styfle/cancel-workflow-action@0.10.0
-        with:
-          access_token: ${{ github.token }}
-      - uses: actions/checkout@v4
-      - uses: dtolnay/rust-toolchain@stable
-      - run: cargo test
-      - run: cargo test --all-features
-
-  test-with-features:
-    name: Test With Features
-    runs-on: ubuntu-latest
     strategy:
       matrix:
-        features: [serde1, tokio1, serde-transport, tcp]
+        serde: ["--features serde1", ""]
+        tokio: ["--features tokio1", ""]
+        serde-transport: ["--features serde-transport", ""]
+        serde-transport-json: ["--features serde-transport-json", ""]
+        serde-transport-bincode: ["--features serde-transport-bincode", ""]
+        tcp: ["--features tcp", ""]
+        unix: ["--features unix", ""]
+        exclude:
+          - serde-transport-json: "--features serde-transport-json"
+            serde-transport: ""
+          - serde-transport-bincode: "--features serde-transport-bincode"
+            serde-transport: ""
+          - serde-transport: "--features serde-transport"
+            tokio: ""
+          - serde-transport: "--features serde-transport"
+            serde: ""
+          - tcp: "--features tcp"
+            serde-transport: ""
+          - unix: "--features unix"
+            serde-transport: ""
     steps:
       - name: Cancel previous
         uses: styfle/cancel-workflow-action@0.10.0
@@ -47,7 +53,11 @@ jobs:
           access_token: ${{ github.token }}
       - uses: actions/checkout@v4
       - uses: dtolnay/rust-toolchain@stable
-      - run: cargo test --manifest-path tarpc/Cargo.toml --features "${{ matrix.example }}"
+      - run: >
+          cargo test --manifest-path tarpc/Cargo.toml
+          ${{ matrix.serde }} ${{ matrix.tokio }} ${{ matrix.serde-transport }}
+          ${{ matrix.serde-transport-json }} ${{ matrix.serde-transport-bincode }}
+          ${{ matrix.tcp }} ${{ matrix.unix }}
 
   list-examples:
     name: List Examples
@@ -118,3 +128,18 @@ jobs:
         with:
           components: clippy
       - run: cargo clippy --all-features -- -D warnings
+
+  # This job succeeds if all other tests and examples succeed. Otherwise, it fails. It is for use in
+  # branch protection rules.
+  test-suite:
+    name: Test Suite
+    runs-on: ubuntu-latest
+    needs: [test, run-example]
+    if: always()
+    steps:
+      - name: All tests ok
+        if: ${{ !(contains(needs.*.result, 'failure')) }}
+        run: exit 0
+      - name: Some tests failed
+        if: ${{ contains(needs.*.result, 'failure') }}
+        run: exit 1
